apiVersion: v1beta1
kind: Deployment
metadata:
  name: sanic-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: db
    spec:
      containers:
        - name: sanic-db-con
          image: namptit307/sanic_db
          imagePullPolicy: IfNotPresent
          pors:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
